name: Automation Test And Build HTTPENV

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-image:
    name: Build Image For Testing
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
      - name: Set up docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build Test Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: ${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
    
  unit-test:
    name: Unit tests in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Unit Testing in Docker
        run: docker run --rm ${{ github.run_id }} echo "run test commands here"

  integration-test:
    name: Integration tests in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Integration Testing in Docker
        run: |
          echo "TESTING_IMAGE=${{ github.run_id }}" > .env
          docker compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from integration-test
          docker compose -f docker-compose.test.yml down

  scan-image:
    name: Scanning image in Docker
    needs: [build-test-image]
    runs-on: ubuntu-latest
    steps: 
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} 
      - name: Run Trivy for all CVEs (non-blocking)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ github.run_id }}
          format: table
          exit-code: 0
    
  build-final-image:
    name: Build and deploy image
    needs: [unit-test, integration-test, scan-image]
    runs-on: ubuntu-latest
    steps: 
      - name: Set up docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: fedryalvindra/httpenv-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=09
      - name: Build Test Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
