name: Automation Test And Build HTTPENV

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-test-image:
    name: Build Test Image & Push to GHCR
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push test image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}/httpenv-automation:${{ github.run_id }}
          target: test
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64

  unit-test:
    name: Unit Tests in GHCR Image
    needs: build-test-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run unit tests
        run: docker run --rm ghcr.io/${{ github.repository }}/httpenv-automation:${{ github.run_id }} echo "Run unit test"

  integration-test:
    name: Integration Tests via Docker Compose
    needs: build-test-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set TESTING_IMAGE env
        run: echo "TESTING_IMAGE=ghcr.io/${{ github.repository }}/httpenv-automation:${{ github.run_id }}" > .env

      - name: Run integration tests
        run: |
          docker compose -f docker-compose.test.yaml up --abort-on-container-exit --exit-code-from integration-test
          docker compose -f docker-compose.test.yaml down || true

  scan-image:
    name: Scan Test Image
    needs: build-test-image
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Trivy for CVEs
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}/httpenv-automation:${{ github.run_id }}
          format: table
          exit-code: 0
    
  build-final-image:
    name: Build and deploy image
    needs: [unit-test, integration-test, scan-image]
    runs-on: ubuntu-latest
    steps: 
      - name: Set up docker QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Metadata for Final Image Build
        id: docker_meta
        uses: docker/metadata-action@v5
        with:
          images: fedryalvindra/httpenv-automation
          flavor: |
            latest=false
          tags: |
            type=raw,value=09
      - name: Build Test Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64
